export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
};

export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
};

export const pageConstants = {
  GET_PAGE_REQUEST: "GET_PAGE_REQUEST",
  GET_PAGE_FAILURE: "GET_PAGE_FAILURE",
  GET_PAGE_SUCCESS: "GET_PAGE_SUCCESS",
  ADD_PAGE_REQUEST: "ADD_PAGE_REQUEST",
  ADD_PAGE_FAILURE: "ADD_PAGE_FAILURE",
  ADD_PAGE_SUCCESS: "ADD_PAGE_SUCCESS",
  UPDATE_PAGE_REQUEST: "UPDATE_PAGE_REQUEST",
  UPDATE_PAGE_FAILURE: "UPDATE_PAGE_FAILURE",
  UPDATE_PAGE_SUCCESS: "UPDATE_PAGE_SUCCESS",
};

export const productConstants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
};

export const initDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",
};

export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};
